version: '3'
services:
  torrent-webhook:
    build: .
    container_name: flask-webhook
    restart: always
    env_file: .env
    ports:
      - 8989:5000
    healthcheck:
      interval: 1m30s
      retries: 3
      test:
        - CMD
        - curl
        - -f
        - http://localhost:5000
      timeout: 10s
    volumes:
      - ${VOLUME_FOLDER}:/files
